name         'camptocamp-postgis'
version      '0.1.1'
dependency   'puppetlabs/postgresql', '>= 3.3.0'
source       'https://github.com/camptocamp/puppet-postgis'
author       'Camptocamp'
license      'Apache 2.0'
summary      'Camptocamp Postgis Module'
description  'Postgis Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-postgis'
